name: CI – test adxl345usb wrapper

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

jobs:
  unit:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout
    - uses: actions/checkout@v4

    # 2. Python environment
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    # 3. Install runtime deps + pytest
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyserial pytest

    # 4. Ensure the script is executable
    - name: chmod +x adxl345usb
      run: chmod +x adxl345usb

    # 5. Run unit tests
    - name: Run pytest
      run: pytest -q
